from .sentinel2_bands import SENTINEL2_BANDS, SENTINEL2_BANDS_INFO
from .landsat_bands import (
    LANDSAT_TM_BANDS,
    LANDSAT_TM_BANDS_INFO,
    LANDSAT_OLI_BANDS,
    LANDSAT_OLI_BANDS_INFO,
)

__all__ = [
    'SENTINEL2_BANDS',
    'SENTINEL2_BANDS_INFO',
    'LANDSAT_TM_BANDS',
    'LANDSAT_TM_BANDS_INFO',
    'LANDSAT_OLI_BANDS',
    'LANDSAT_OLI_BANDS_INFO',
]
